import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { CPDEntry } from "@/lib/store";

// Helper to deduce domain (Shared logic)
export const getDomain = (tags: string[] | undefined) => {
  const t = (tags || []).join(" ").toLowerCase();
  if (t.includes("safety") || t.includes("quality")) return "Safety & Quality";
  if (t.includes("communication") || t.includes("teamwork")) return "Communication, Partnership & Teamwork";
  if (t.includes("trust")) return "Maintaining Trust";
  return "Knowledge, Skills & Performance";
};

// Styles for a professional Medical Portfolio look
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.5,
    color: '#334155'
  },
  header: {
    marginBottom: 20,
    borderBottom: '2px solid #0e7490',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end'
  },
  brand: {
    fontSize: 10,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 1
  },
  date: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0e7490'
  },
  titleSection: {
    marginBottom: 20
  },
  label: {
    fontSize: 8,
    color: '#64748b',
    textTransform: 'uppercase',
    fontWeight: 'bold',
    marginBottom: 4
  },
  question: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    marginBottom: 8
  },
  metaRow: {
    flexDirection: 'row',
    marginBottom: 20,
    gap: 20,
    borderTop: '1px solid #e2e8f0',
    borderBottom: '1px solid #e2e8f0',
    paddingVertical: 8
  },
  metaItem: {
    flexDirection: 'column'
  },
  metaValue: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a'
  },
  section: {
    marginBottom: 15
  },
  content: {
    fontSize: 11,
    textAlign: 'justify',
    color: '#334155'
  },
  reflectionBox: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#f0fdf4',
    borderLeft: '3px solid #16a34a',
    borderRadius: 4
  },
  reflectionText: {
    fontStyle: 'italic',
    color: '#14532d'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#cbd5e1',
    borderTop: '1px solid #f1f5f9',
    paddingTop: 10
  }
});

interface CpdPdfProps {
  entry: CPDEntry;
}

export const CpdPdfDocument = ({ entry }: CpdPdfProps) => {
  const domain = getDomain(entry.tags);
  const duration = entry.duration || 10;
  const credits = (duration / 60).toFixed(2);
  const dateStr = new Date(entry.timestamp).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric'
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.date}>{dateStr}</Text>
          <Text style={styles.brand}>Umbil Learning Log</Text>
        </View>

        {/* Title */}
        <View style={styles.titleSection}>
          <Text style={styles.label}>Learning Activity</Text>
          <Text style={styles.question}>{entry.question}</Text>
        </View>

        {/* Meta Data */}
        <View style={styles.metaRow}>
          <View style={styles.metaItem}>
            <Text style={styles.label}>GMC Domain</Text>
            <Text style={styles.metaValue}>{domain}</Text>
          </View>
          <View style={styles.metaItem}>
             <Text style={styles.label}>Credits</Text>
             <Text style={styles.metaValue}>{credits} ({duration} mins)</Text>
          </View>
          <View style={styles.metaItem}>
             <Text style={styles.label}>Type</Text>
             <Text style={styles.metaValue}>{(entry.tags || []).join(", ") || "General"}</Text>
          </View>
        </View>

        {/* Content */}
        <View style={styles.section}>
          <Text style={styles.label}>Description & Outcome</Text>
          <Text style={styles.content}>{entry.answer}</Text>
        </View>

        {/* Reflection */}
        {entry.reflection && (
          <View style={styles.reflectionBox}>
            <Text style={{...styles.label, color: '#166534', marginBottom: 5}}>Reflection</Text>
            <Text style={styles.reflectionText}>{entry.reflection}</Text>
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by Umbil • Verified Learning Entry • {entry.id}</Text>
        </View>

      </Page>
    </Document>
  );
};